### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by LesoR** [rguedes/laravel-wargaming-auth#1]
I proceed to install, in _composer.json_ added _"rguedes / laravel-wargaming-auth": "2. *"_
Perform _composer install_
And an error is issued
`Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package rguedes/laravel-wargaming-auth could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.`

Please, help

**Comment by rguedes** [comment]
add this to composer.json:

> "repositories": [
>         {
>             "type":"vcs",
>             "url": "https://github.com/rguedes/laravel-wargaming-auth.git"
>         }
> ]

and add this to require:

> "rguedes/laravel-wargaming-auth": "dev-master",

**Comment by LesoR** [comment]
After installation and publication, the php artisan commands stopped working for me

**Comment by LesoR** [comment]
Understood, tnx bro.
